apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
        - name: {{ .Values.postgres.name }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.env.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.env.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgres.env.db }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}