apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-app
  template:
    metadata:
      labels:
        app: tech-app
    spec:
      containers:
        - name: tech-app
          image: wolwer/tech-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/mydatabase
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: my-secret-pw
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 380
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 380
            periodSeconds: 30